/**
 * LLC Operating Agreement template generator.
 *
 * Deterministic string-builder that produces a customized operating
 * agreement draft based on user input. This is NOT legal advice. Every
 * generated document includes a prominent disclaimer urging review by a
 * licensed attorney in the user's jurisdiction.
 */

export type MemberStructure = "single" | "multi";
export type ManagementStructure = "member-managed" | "manager-managed";

export interface Member {
  name: string;
  contribution: number;
  ownershipPct: number;
}

export interface LlcAgreementInput {
  entityName: string;
  state: string;
  formationDate: string; // YYYY-MM-DD
  principalOffice: string;
  purpose: string;
  memberStructure: MemberStructure;
  managementStructure: ManagementStructure;
  members: Member[];
  registeredAgent?: string;
}

/* ─────────────────────────────────────────────────────────────── */

function money(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }).format(n);
}

function today(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatDate(iso: string): string {
  if (!iso) return "[formation date]";
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

/* ─────────────────────────────────────────────────────────────── */

const DISCLAIMER = `
DISCLAIMER AND NOTICE

This document is a template generated by a free tool at YorkSims.com. It is
not legal advice and does not create an attorney-client relationship.
State-specific requirements, tax elections, and fiduciary standards vary
significantly by jurisdiction and by the circumstances of each business.
Before executing this or any operating agreement, review the document with
a licensed attorney in your state and confirm it meets the requirements for
your entity, members, and operations.

Generated: ${today()}
Source: https://yorksims.com/tools/llc-operating-agreement-generator
`.trim();

/* ─────────────────────────────────────────────────────────────── */

export function generateLlcAgreement(input: LlcAgreementInput): string {
  const {
    entityName,
    state,
    formationDate,
    principalOffice,
    purpose,
    memberStructure,
    managementStructure,
    members,
    registeredAgent,
  } = input;

  const isSingle = memberStructure === "single" || members.length === 1;
  const isManagerManaged = managementStructure === "manager-managed";

  const memberNoun = isSingle ? "Sole Member" : "Member";
  const memberNounPlural = isSingle ? "Sole Member" : "Members";
  const companyShort = `the "Company"`;

  const totalContribution = members.reduce(
    (sum, m) => sum + (m.contribution || 0),
    0
  );

  const memberBlock = members
    .map(
      (m, i) =>
        `  ${String(i + 1).padStart(2, "0")}.  ${m.name} — Capital Contribution: ${money(
          m.contribution
        )} — Ownership: ${m.ownershipPct.toFixed(2)}%`
    )
    .join("\n");

  const signatureLines = members
    .map(
      (m) =>
        `
____________________________________
${m.name}
${memberNoun}
Date: ______________________
`.trim()
    )
    .join("\n\n");

  return `
${DISCLAIMER}

══════════════════════════════════════════════════════════════════════════════

OPERATING AGREEMENT
OF
${entityName.toUpperCase()}

A ${state} Limited Liability Company

══════════════════════════════════════════════════════════════════════════════

THIS OPERATING AGREEMENT (this "Agreement") of ${entityName} (${companyShort}),
a limited liability company organized under the laws of the State of ${state},
is entered into and effective as of ${formatDate(formationDate)}, by and
among the ${memberNounPlural} signing below.


ARTICLE 1 — FORMATION

1.1 Formation. The Company was formed as a limited liability company under
    the laws of the State of ${state} by the filing of Articles of
    Organization with the Secretary of State on ${formatDate(formationDate)}.

1.2 Name. The name of the Company is ${entityName}.

1.3 Principal Office. The principal office of the Company shall be located
    at ${principalOffice}, or at such other place as the ${memberNounPlural}
    may from time to time designate.

1.4 Registered Agent. The Company's registered agent and registered office
    shall be as set forth in the Articles of Organization${
      registeredAgent ? `: ${registeredAgent}` : ""
    }, and may be changed from time to time in accordance with the laws of
    the State of ${state}.

1.5 Term. The Company shall commence on the date of filing of the Articles
    of Organization and shall continue in perpetuity unless sooner
    dissolved in accordance with this Agreement or applicable law.


ARTICLE 2 — PURPOSE AND POWERS

2.1 Purpose. The purpose of the Company is to engage in ${purpose}, and any
    other lawful business or activity for which a limited liability company
    may be organized under the laws of the State of ${state}.

2.2 Powers. The Company shall have all powers necessary or convenient to
    effect the purposes for which the Company is formed, including all
    powers granted to limited liability companies under the laws of the
    State of ${state}.


ARTICLE 3 — MEMBERS AND CAPITAL

3.1 ${memberNounPlural}. The ${memberNounPlural} of the Company, together
    with their respective initial Capital Contributions and ownership
    interests (expressed as Percentage Interests), are as follows:

${memberBlock}

    Total Capital Contributions: ${money(totalContribution)}

3.2 Additional Contributions. No ${memberNoun} shall be required to make
    additional Capital Contributions to the Company, unless otherwise
    agreed to in writing by all ${memberNounPlural}.

3.3 Capital Accounts. A separate Capital Account shall be maintained for
    each ${memberNoun} in accordance with applicable tax regulations.

3.4 No Interest. No interest shall be paid on any Capital Contribution or
    on any balance in any ${memberNoun}'s Capital Account.


ARTICLE 4 — MANAGEMENT

${
  isManagerManaged
    ? `4.1 Management Vested in Manager. The business and affairs of the Company
    shall be managed by one or more Managers. The initial Manager(s) shall
    be designated by the ${memberNounPlural}. The Manager(s) shall have
    full and exclusive authority to manage the business of the Company.

4.2 Authority of Manager. Subject to any limitations set forth in this
    Agreement or applicable law, each Manager shall have full power and
    authority to bind the Company and to execute documents on its behalf.

4.3 Removal and Replacement. A Manager may be removed, with or without
    cause, by the affirmative vote of ${
      isSingle ? "the Sole Member" : "Members holding a majority of the Percentage Interests"
    }.`
    : `4.1 Management by Members. The business and affairs of the Company shall
    be managed by its ${memberNounPlural}. Except as otherwise provided in
    this Agreement, all decisions of the Company shall be made by ${
      isSingle ? "the Sole Member" : "the Members holding a majority of the Percentage Interests"
    }.

4.2 Authority of Members. Each ${memberNoun} shall have full power and
    authority to bind the Company within the scope of the Company's
    ordinary course of business.

4.3 Major Decisions. Notwithstanding Section 4.1, the following actions
    shall require the unanimous written consent of all ${memberNounPlural}:
      (a) admitting a new ${memberNoun};
      (b) dissolving the Company;
      (c) incurring indebtedness in excess of ${money(50000)};
      (d) selling all or substantially all of the Company's assets;
      (e) amending this Agreement.`
}


ARTICLE 5 — ALLOCATIONS AND DISTRIBUTIONS

5.1 Allocations. Profits and losses of the Company for each fiscal year
    shall be allocated to the ${memberNounPlural} in proportion to their
    respective Percentage Interests.

5.2 Distributions. Distributions of cash or other assets shall be made to
    the ${memberNounPlural} in proportion to their respective Percentage
    Interests, at such times as ${
      isSingle
        ? "the Sole Member determines"
        : "determined by the Members holding a majority of the Percentage Interests"
    }.

5.3 Tax Distributions. To the extent the Company has available cash, the
    Company shall make cash distributions to each ${memberNoun} in an amount
    sufficient to satisfy such ${memberNoun}'s estimated federal and state
    income tax liability resulting from the Company's operations for such
    fiscal year, calculated at an assumed rate reasonably determined by the
    ${isManagerManaged ? "Manager" : memberNounPlural}.


ARTICLE 6 — TRANSFERS AND NEW MEMBERS

6.1 Restrictions on Transfer. No ${memberNoun} may sell, assign, pledge, or
    otherwise transfer all or any portion of their Membership Interest
    without the prior written consent of ${
      isSingle
        ? "any additional Members that may be admitted in the future"
        : "all other Members"
    }, except as permitted by this Article.

6.2 Right of First Refusal. Before any ${memberNoun} (a "Selling Member")
    may transfer all or any portion of their Membership Interest to a third
    party, the Selling Member shall first offer such interest to the Company
    and then to the remaining ${memberNounPlural} at the same price and
    terms offered by the third party.

6.3 Admission of New Members. New members may be admitted only upon the
    unanimous written consent of all existing ${memberNounPlural} and upon
    execution of a joinder agreeing to be bound by this Agreement.


ARTICLE 7 — BOOKS, RECORDS, AND TAX

7.1 Books and Records. The Company shall maintain complete and accurate
    books and records of account at its principal office. Each ${memberNoun}
    shall have the right to inspect and copy such books and records at
    reasonable times.

7.2 Fiscal Year. The fiscal year of the Company shall end on December 31,
    unless otherwise changed by the ${
      isManagerManaged ? "Manager" : memberNounPlural
    }.

7.3 Tax Classification. The Company shall be classified${
      isSingle
        ? " as a disregarded entity for federal income tax purposes"
        : " as a partnership for federal income tax purposes"
    }, unless and until the ${
      isSingle ? "Sole Member" : memberNounPlural
    } elect otherwise.

7.4 Tax Matters Representative. The ${
      isSingle ? "Sole Member" : "Members"
    } shall designate a "Partnership Representative" in accordance with the
    Internal Revenue Code.


ARTICLE 8 — DISSOLUTION AND WINDING UP

8.1 Events of Dissolution. The Company shall be dissolved upon the first
    to occur of:
      (a) the written consent of ${
        isSingle ? "the Sole Member" : "all Members"
      };
      (b) the entry of a decree of judicial dissolution; or
      (c) any other event causing dissolution under applicable law.

8.2 Winding Up. Upon dissolution, the Company's affairs shall be wound up,
    its assets liquidated, and the proceeds distributed in the following
    order of priority: (i) to creditors of the Company; (ii) to the
    ${memberNounPlural} in proportion to their positive Capital Account
    balances; and (iii) to the ${memberNounPlural} in accordance with their
    Percentage Interests.


ARTICLE 9 — LIABILITY AND INDEMNIFICATION

9.1 Limitation of Liability. No ${memberNoun}${
    isManagerManaged ? " or Manager" : ""
  } shall be personally liable for any debts, obligations, or liabilities
    of the Company beyond such person's Capital Contribution, except as
    otherwise required by law.

9.2 Indemnification. The Company shall indemnify each ${memberNoun}${
    isManagerManaged ? " and Manager" : ""
  } against any loss, damage, or expense (including reasonable attorneys'
    fees) incurred in connection with any action or proceeding arising out
    of such person's service to the Company, except where such loss,
    damage, or expense results from willful misconduct, gross negligence,
    or a knowing violation of law.


ARTICLE 10 — MISCELLANEOUS

10.1 Governing Law. This Agreement shall be governed by and construed in
     accordance with the laws of the State of ${state}, without regard to
     its conflict of laws principles.

10.2 Entire Agreement. This Agreement constitutes the entire agreement
     among the ${memberNounPlural} with respect to the subject matter
     hereof and supersedes all prior or contemporaneous agreements,
     whether written or oral.

10.3 Amendments. This Agreement may be amended only by a writing signed by
     ${isSingle ? "the Sole Member" : "all Members"}.

10.4 Severability. If any provision of this Agreement is held to be
     invalid, illegal, or unenforceable, the remaining provisions shall
     continue in full force and effect.

10.5 Counterparts. This Agreement may be executed in one or more
     counterparts (including electronic signatures), each of which shall
     be deemed an original, and all of which together shall constitute one
     and the same instrument.

10.6 Notices. All notices under this Agreement shall be in writing and
     shall be deemed given when delivered personally, by email with
     confirmation of receipt, or by overnight courier to the address of
     the recipient as shown on the Company's records.


SIGNATURES

IN WITNESS WHEREOF, the undersigned ${memberNounPlural} have executed this
Operating Agreement as of the date first written above.


${signatureLines}


══════════════════════════════════════════════════════════════════════════════

${DISCLAIMER}
`.trim();
}

/* ─────────────────────────────────────────────────────────────── */

/** Produce a shareable HTML document (printable, downloadable). */
export function generateLlcAgreementHtml(
  input: LlcAgreementInput
): string {
  const text = generateLlcAgreement(input);
  const safe = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Operating Agreement — ${input.entityName}</title>
<style>
  @page { margin: 1in; }
  body {
    font-family: "Times New Roman", Times, serif;
    font-size: 12pt;
    line-height: 1.55;
    color: #111;
    max-width: 780px;
    margin: 48px auto;
    padding: 0 24px;
  }
  pre {
    white-space: pre-wrap;
    word-wrap: break-word;
    font-family: "Times New Roman", Times, serif;
    font-size: 12pt;
    line-height: 1.55;
  }
  .print-bar {
    position: sticky;
    top: 0;
    background: #fff;
    border-bottom: 1px solid #ddd;
    padding: 12px 0;
    margin-bottom: 24px;
    display: flex;
    gap: 12px;
    justify-content: flex-end;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  .print-bar button {
    padding: 8px 16px;
    border: 1px solid #111;
    background: #fff;
    font-size: 13px;
    cursor: pointer;
    border-radius: 4px;
  }
  .print-bar button:hover { background: #111; color: #fff; }
  @media print { .print-bar { display: none; } }
</style>
</head>
<body>
<div class="print-bar">
  <button onclick="window.print()">Print / Save as PDF</button>
</div>
<pre>${safe}</pre>
</body>
</html>`;
}
